### ISSUE TITLE
shards.info v2.0

### ISSUE THREAD

**Issue by mamantoha** [mamantoha/shards-info#37]
# TODO

- [x] https://github.com/mamantoha/shards-info/pull/36
- [x] Select hosting - DigitalOcean 
- [x] Select Crystal ORM - [clear](github.com/anykeyh/clear)
- [x] PostgreSQL Full Text Search
- [x] Background task runner
- [x] Periodic (CRON) jobs
- [x] Sync with Github
- [x] Sync with Gitlab

**Comment by mamantoha** [comment]
Done
